# 行列積のスクラッチ

# 【問題1】行列積を手計算する

以下のような行列A、Bを考えます。
$$
  \boldsymbol{A} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {ccc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{ccc}
            -1 &  2 &  3 \\
             4 & -5 &  6 \\
             7 &  8 & -9 \\
        \end{array}\right] \quad
        ,
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
             0 &  2 &  1 \\
             0 &  2 & -8 \\
             2 &  9 & -1 \\
        \end{array}\right] \quad
$$

NumPyで表すと次のようになります。
```py
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
```
AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。

## 公式
$$
\left[\begin{array}{ccc}
     a_1 & a_2 & a_3 \\
     a_4 & a_5 & a_6 \\
     a_7 & a_8 & a_9 \\
\end{array}\right] \quad
*
\left[\begin{array}{ccc}
     b_1 & b_2 & b_3 \\
     b_4 & b_5 & b_6 \\
     b_7 & b_8 & b_9 \\
\end{array}\right] \quad 
$$
$$
= 
\left[\begin{array}{ccc}
     a_1*b_1+a_2*b_4+a_3*b_7 & a_1+b_2+a_2*b_5+a_3*b_8 & a_1*b_3a+a_2*b_6+a_3*b_9 \\
     a_4*b_1+a_5*b_4+a_6*b_7 & a_4+b_2+a_5*b_5+a_6*b_8 & a_4*b_3a+a_5*b_6+a_6*b_9 \\
     a_7*b_1+a_8*b_4+a_9*b_7 & a_7+b_2+a_8*b_5+a_9*b_8 & a_7*b_3a+a_8*b_6+a_9*b_9 \\
        \end{array}\right] \quad       
$$


## 計算過程

上記の公式にしたがって計算すると、、、、

$$
  \left[\begin{array}{ccc}
            -1 &  2 &  3 \\
             4 & -5 &  6 \\
             7 &  8 & -9 \\
        \end{array}\right] \quad
 *
        \left[\begin{array}{ccc}
             0 &  2 &  1 \\
             0 &  2 & -8 \\
             2 &  9 & -1 \\
        \end{array}\right] \quad
$$


$$
= 
\left[\begin{array}{ccc}
     -1* 0+ 2* 0+ 3* 2 & -1* 2+ 2* 2+ 3* 9 & -1* 1+ 2*-8+ 3*-1 \\
      4* 0+-5* 0+ 6* 2 &  4* 2+-5* 2+ 6* 9 &  4* 1+-5*-8+ 6*-1 \\
      7* 0+ 8* 0+-9* 2 &  7+ 2+ 8* 2+-9* 9 &  7* 1+ 8*-8+-9*-1 \\
        \end{array}\right] \quad       
$$


$$
= 
\left[\begin{array}{ccc}
     0+0+6 & -2+4+27 & -1-16-3 \\
     0+0+12 & 8-10+54 & 4+40-6 \\
     0+0-18 & 14+16-81 & 7-64+9 \\
        \end{array}\right] \quad       
$$

となり、答えは下記の通り


$$
        \boldsymbol{Ans} =
        \left[\begin{array}{ccc}
             6 &  29 & -20 \\
            12 &  52 &  38 \\
           -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

## 行列積のスクラッチ実装
np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

In [7]:
#np.matmul()を使ってみる
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

q2_ans = np.matmul(a_ndarray,b_ndarray)
print(q2_ans)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [6]:
#@も使ってみる
q2_ans2 = a_ndarray @ b_ndarray
print(q2_ans2)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

- 行列Aの(0,0)の要素 $a_{0,0}$ と行列Bの(0,0)の要素 $b_{0,0}$を掛け合わせる

- 行列Aの(0,1)の要素 $a_{0,1}$ と行列Bの(1,0)の要素 $b_{1,0}$ を掛け合わせる

- 行列Aの(0,2)の要素 $a_{0,2}$ と行列Bの(2,0)の要素 $b_{2,0}$ を掛け合わせる
- それらの値を全て足し合わせる

数式で表すと
$$
  \sum_{k=0}^{2}a_{0,k}b_{k,0} \quad
$$
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [60]:
q3_sigma_array = []
for i in range(3):
    q3_sigma_array.append(a_ndarray[0,i]*b_ndarray[i,0])
print(q3_sigma_array)

[0, 0, 6]


In [45]:
q3_sigma_array = []
for i in range(3):
    q3_sigma_array.append(a_ndarray[0,i]*b_ndarray[i,0])
print("行列A,Bにおける上記数式の計算結果は{}です".format(sum(q3_sigma_array)))

行列A,Bにおける上記数式の計算結果は6です


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である 3×3 の行列Cの各要素 $c_{i,j}$は数式で表すと次のようになります。
$$
  c_{i,j} = \sum_{k=0}^{2}a_{i,k}b_{k,j} \quad
$$
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス 
$i$や $j$を1増やすと、次の行や列に移ることができます。

In [132]:
def compute_gyouretuseki(gyouretu_a, gyouretu_b):
    temp_calculation = [] #1要素計算リスト
    line_elements = [] #n行における要素リスト
    compute_gyouretuseki = [] #行列積リスト
    
    if gyouretu_a.shape[0] == gyouretu_b.shape[1]:
        for i in range(gyouretu_a.shape[0]):
            line_elements = [] #n行における要素リストの初期化
            for j in range(gyouretu_a.shape[0]):
                temp_calculation = [] #１要素計算リストの初期化
                for k in range(gyouretu_a.shape[0]):
                    temp_calculation.append(gyouretu_a[i,k]*gyouretu_b[k,j]) #1要素計算
                line_elements.append(sum(temp_calculation)) #シグマ計算と結果格納
            compute_gyouretuseki.append(line_elements) #2次元配列へ
    else:
        compute_gyouretuseki = "エラー：gyouretu_aの列数とgyouretu_bの行数が異なるため計算できません"
    return compute_gyouretuseki

print(compute_gyouretuseki(a_ndarray, b_ndarray))

##問題５を含む

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


### 模範解答

In [4]:
import numpy as np
def matrix_product_q4_1(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_product_q4_1(a_ndarray, b_ndarray)))

計算結果
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

## 行列積が定義されない組み合わせの行列

$$
  \boldsymbol{D} =
        % ベクトルや行列は"left["と"right]"でベクトルや行列の括弧を作る
        % 括弧内に"array"環境を展開する
        % {ccc}の形で中央揃え、縦線、中央揃え*2の並びに出来る
        \left[\begin{array}{ccc}
            -1 &  2 &  3 \\
             4 & -5 &  6 \\
        \end{array}\right] \quad
        ,
    \boldsymbol{E-} =
        \left[\begin{array}{ccc}
            -9 &  8 &  7 \\
             6 & -5 &  4 \\
        \end{array}\right] \quad
$$
```py
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
```

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

In [134]:
#上記の行列Aの列数と行列Bの行数が異なる行列を用意
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

#上記の例でテスト
print(compute_gyouretuseki(d_ndarray_,e_ndarray))

エラー：gyouretu_aの列数とgyouretu_bの行数が異なるため計算できません


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [131]:
t_e_ndarray = np.transpose(e_ndarray) #行列E-を転置

print("行列積は",compute_gyouretuseki(d_ndarray_,t_e_ndarray),"です。")

行列積は [[25, -16], [-76, 49]] です。
